audits:
  - size
  - lighthouse
  - unused-source

configs:
  buildDir: dist

  lighthouse:
    outputHtml: gimbal/lighthouse.html
    skipAudits:
      - uses-http2
      - redirects-http
      - is-on-https
      - uses-long-cache-ttl
      - uses-text-compression
    threshold:
      accessibility: 90
      "best-practices": 100
      performance: 80
      seo: 100
      pwa: 95

  size:
    - path: ./dist/
      maxSize: 10 MB

outputs:
  # Mostrar apenas falhas no CLI
  cli:
    onlyFailures: true
  html: gimbal/results.html
  json: gimbal/results.json
  markdown: gimbal/results.md
